[package]
name = "zero_to_prod"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.0.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
