[advisories]
ignore = [
    "RUSTSEC-2024-0384",  # instant is unmaintained
    "RUSTSEC-2024-0436",  # paste is unmaintained  
    "RUSTSEC-2025-0009",  # ring AES functions vulnerability
    "RUSTSEC-2025-0010",  # ring versions prior to 0.17 unmaintained
    "RUSTSEC-2024-0336",  # rustls infinite loop issue
    "RUSTSEC-2024-0363",  # SQLx binary protocol issue
    "RUSTSEC-2023-0086",  # lexical-core soundness issues (from config crate)
    "RUSTSEC-2024-0320",  # yaml-rust is unmaintained (from config crate)
]
