# The name of your workflow. GitHub displays the names of your workflows on your repository's "Actions" tab
name: Rust

# To automatically trigger the workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  SQLX_VERSION: 0.6.3
  SQLX_FEATURES: "rustls,postgres"
  APP_USER: app
  APP_USER_PWD: secret
  APP_DB_NAME: newsletter

# A workflow run is made up of one or more jobs, which run in parallel by default
# Each job runs in a runner environment specified by runs-on
jobs:
  # Unique identifier of our job (`job_id`)
  test:
    # Sets the name `Test` for the job, which is displayed in the GitHub UI
    name: Test
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Service containers to run alongside the `test` container job
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image - NOTE: Database is created automatically by service
        image: postgres:14
        # Environment variables scoped only for the `postgres` element
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: newsletter  # Creates the newsletter database automatically
        # When you map ports using the ports keyword, GitHub uses the --publish command to publish the container's ports to the Docker host
        # Opens tcp port 5432 on the host and service container
        ports:
          - 5432:5432
      # Redis service container
      redis:
        image: redis:7
        ports:
          - 6379:6379
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v4

      # This GitHub Action installs a Rust toolchain using rustup
      - name: Install the Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      # Install sqlx-cli for running migrations
      - name: Install sqlx-cli
        run: |
          cargo install sqlx-cli \
            --version=${{ env.SQLX_VERSION }} \
            --features ${{ env.SQLX_FEATURES }} \
            --no-default-features \
            --locked

      # Wait for Postgres service to be ready before proceeding
      - name: Wait for Postgres to be ready
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client
          # Use pg_isready to wait for the service to be available
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for postgres..."
            sleep 2
          done
          echo "Postgres is ready!"
        env:
          PGPASSWORD: password

      # Wait for Redis to be ready
      - name: Wait for Redis to be ready
        run: |
          sudo apt-get install -y redis-tools
          until redis-cli -h localhost -p 6379 ping | grep -q PONG; do
            echo "Waiting for Redis..."
            sleep 2
          done
          echo "Redis is ready!"

      # Run database migrations BEFORE any tests
      - name: Run Migrations
        run: sqlx migrate run
        env:
          DATABASE_URL: "postgres://postgres:password@localhost:5432/${{ env.APP_DB_NAME }}"

      # Create app user after migrations (tests may need this user)
      - name: Create app user in Postgres
        run: |
          # Create the application user
          CREATE_QUERY="CREATE USER ${{ env.APP_USER }} WITH PASSWORD '${{ env.APP_USER_PWD }}';"
          PGPASSWORD="password" psql -U "postgres" -h "localhost" -p "5432" -c "${CREATE_QUERY}"

          # Grant create db privileges to the app user
          GRANT_QUERY="ALTER USER ${{ env.APP_USER }} CREATEDB;"
          PGPASSWORD="password" psql -U "postgres" -h "localhost" -p "5432" -c "${GRANT_QUERY}"

          # Grant connect and usage on the newsletter DB
          GRANT_CONNECT_QUERY="GRANT CONNECT ON DATABASE ${{ env.APP_DB_NAME }} TO ${{ env.APP_USER }};"
          PGPASSWORD="password" psql -U "postgres" -h "localhost" -p "5432" -d "${{ env.APP_DB_NAME }}" -c "${GRANT_CONNECT_QUERY}"

      # Now run tests - database and Redis are guaranteed to be ready
      - name: Run tests
        env:
          APP_DATABASE__USERNAME: ${{ env.APP_USER }}
          APP_DATABASE__PASSWORD: ${{ env.APP_USER_PWD }}
          APP_DATABASE__HOST: "localhost"
          APP_DATABASE__PORT: "5432"
        run: cargo test
      
      # Check sqlx metadata consistency
      - name: Check that queries are fresh
        env:
          # Force SQLx to use offline mode and ignore any DATABASE_URL from secrets
          SQLX_OFFLINE: true
        run: cargo sqlx prepare --check -- --workspace --all-targets

  # `fmt` container job
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install the Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Enforce formatting
        run: cargo fmt --check

  # `clippy` container job
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    env:
      # This environment variable forces sqlx to use its offline mode,
      # which means that it will not attempt to connect to a database
      # when running the tests. It'll instead use the cached query results.
      # We check that the cached query results are up-to-date in another job,
      # to speed up the overall CI pipeline.
      # This will all be covered in detail in chapter 5.
      SQLX_OFFLINE: true
    steps:
      - uses: actions/checkout@v4
      - name: Install the Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - name: Linting
        run: cargo clippy -- -D warnings

  # `coverage` container job
  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: newsletter  # Create newsletter database directly
        ports:
          - 5432:5432
      # Redis service for coverage job
      redis:
        image: redis:7
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - name: Install the Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: llvm-tools-preview
      - name: Install sqlx-cli
        run: cargo install sqlx-cli
          --version=${{ env.SQLX_VERSION }}
          --features ${{ env.SQLX_FEATURES }}
          --no-default-features
          --locked
      
      # Wait for Postgres and run migrations for coverage job too
      - name: Wait for Postgres to be ready
        run: |
          sudo apt-get install postgresql-client
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for postgres..."
            sleep 2
          done
        env:
          PGPASSWORD: password

      # Wait for Redis in coverage job
      - name: Wait for Redis to be ready
        run: |
          sudo apt-get install -y redis-tools
          until redis-cli -h localhost -p 6379 ping | grep -q PONG; do
            echo "Waiting for Redis..."
            sleep 2
          done
          echo "Redis is ready!"

      - name: Run Migrations
        run: sqlx migrate run
        env:
          DATABASE_URL: "postgres://postgres:password@localhost:5432/${{ env.APP_DB_NAME }}"

      - name: Create app user in Postgres
        run: |
          # Create the application user
          CREATE_QUERY="CREATE USER ${APP_USER} WITH PASSWORD '${APP_USER_PWD}';"
          PGPASSWORD="password" psql -U "postgres" -h "localhost" -c "${CREATE_QUERY}"

          # Grant create db privileges to the app user
          GRANT_QUERY="ALTER USER ${APP_USER} CREATEDB;"
          PGPASSWORD="password" psql -U "postgres" -h "localhost" -c "${GRANT_QUERY}"
      
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      - name: Generate report
        run: cargo llvm-cov report --html --output-dir coverage
      - uses: actions/upload-artifact@v4
        with:
          name: "Coverage report"
          path: coverage/
